# Generated by Django 5.1.6 on 2025-04-10 01:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='users/profile'),
            preserve_default=False,
        ),
    ]
