# Generated by Django 5.1.6 on 2025-03-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('all', 'all'), ('tech', 'Technology'), ('science', 'Science'), ('arts', 'Arts'), ('business', 'Business'), ('finance', 'Finance'), ('health', 'Health & Wellness'), ('education', 'Education'), ('sports', 'Sports'), ('gaming', 'Gaming'), ('entertainment', 'Entertainment'), ('travel', 'Travel & Tourism'), ('food', 'Food & Cooking'), ('fashion', 'Fashion & Beauty'), ('automobile', 'Automobiles'), ('real_estate', 'Real Estate'), ('music', 'Music'), ('movies', 'Movies & TV Shows'), ('cryptocurrency', 'Cryptocurrency'), ('environment', 'Environment & Sustainability'), ('ai', 'Artificial Intelligence')], max_length=20)),
                ('country', models.CharField(choices=[('NG', 'Nigeria')], default='NG', max_length=2)),
                ('state', models.CharField(choices=[('All', 'All'), ('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara'), ('Abuja', 'Abuja')], max_length=20)),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['state', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], decimal_places=1, max_digits=2)),
                ('review', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product_description', models.TextField(max_length=250)),
                ('product_price', models.PositiveIntegerField()),
                ('product_category', models.CharField(choices=[('all', 'all'), ('tech', 'Technology'), ('science', 'Science'), ('arts', 'Arts'), ('business', 'Business'), ('finance', 'Finance'), ('health', 'Health & Wellness'), ('education', 'Education'), ('sports', 'Sports'), ('gaming', 'Gaming'), ('entertainment', 'Entertainment'), ('travel', 'Travel & Tourism'), ('food', 'Food & Cooking'), ('fashion', 'Fashion & Beauty'), ('automobile', 'Automobiles'), ('real_estate', 'Real Estate'), ('music', 'Music'), ('movies', 'Movies & TV Shows'), ('cryptocurrency', 'Cryptocurrency'), ('environment', 'Environment & Sustainability'), ('ai', 'Artificial Intelligence')], default='all', max_length=50)),
                ('product_country', models.CharField(choices=[('NG', 'Nigeria')], default='All', max_length=50)),
                ('product_state', models.CharField(choices=[('All', 'All'), ('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara'), ('Abuja', 'Abuja')], default='All', max_length=50)),
                ('product_city', models.CharField(choices=[('All', 'All'), ('Aba', 'Aba'), ('Umuahia', 'Umuahia'), ('Yola', 'Yola'), ('Mubi', 'Mubi'), ('Uyo', 'Uyo'), ('Eket', 'Eket'), ('Awka', 'Awka'), ('Onitsha', 'Onitsha'), ('Nnewi', 'Nnewi'), ('Bauchi', 'Bauchi'), ('Azare', 'Azare'), ('Yenagoa', 'Yenagoa'), ('Makurdi', 'Makurdi'), ('Otukpo', 'Otukpo'), ('Maiduguri', 'Maiduguri'), ('Biu', 'Biu'), ('Calabar', 'Calabar'), ('Ikom', 'Ikom'), ('Warri', 'Warri'), ('Asaba', 'Asaba'), ('Sapele', 'Sapele'), ('Abakaliki', 'Abakaliki'), ('Benin City', 'Benin City'), ('Auchi', 'Auchi'), ('Ado Ekiti', 'Ado Ekiti'), ('Enugu', 'Enugu'), ('Nsukka', 'Nsukka'), ('Gombe', 'Gombe'), ('Owerri', 'Owerri'), ('Orlu', 'Orlu'), ('Dutse', 'Dutse'), ('Kaduna', 'Kaduna'), ('Zaria', 'Zaria'), ('Kano', 'Kano'), ('Wudil', 'Wudil'), ('Katsina', 'Katsina'), ('Funtua', 'Funtua'), ('Birnin Kebbi', 'Birnin Kebbi'), ('Lokoja', 'Lokoja'), ('Anyigba', 'Anyigba'), ('Ilorin', 'Ilorin'), ('Offa', 'Offa'), ('Ikeja', 'Ikeja'), ('Badagry', 'Badagry'), ('Epe', 'Epe'), ('Ikorodu', 'Ikorodu'), ('Surulere', 'Surulere'), ('Lafia', 'Lafia'), ('Keffi', 'Keffi'), ('Minna', 'Minna'), ('Bida', 'Bida'), ('Abeokuta', 'Abeokuta'), ('Sagamu', 'Sagamu'), ('Akure', 'Akure'), ('Ondo', 'Ondo'), ('Osogbo', 'Osogbo'), ('Ile Ife', 'Ile Ife'), ('Ibadan', 'Ibadan'), ('Ogbomoso', 'Ogbomoso'), ('Jos', 'Jos'), ('Port Harcourt', 'Port Harcourt'), ('Bonny', 'Bonny'), ('Sokoto', 'Sokoto'), ('Jalingo', 'Jalingo'), ('Damaturu', 'Damaturu'), ('Potiskum', 'Potiskum'), ('Gusau', 'Gusau'), ('Garki', 'Garki'), ('Maitama', 'Maitama'), ('Wuse', 'Wuse')], default='All', max_length=50)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_provider_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], decimal_places=1, max_digits=2)),
                ('review', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_image', models.ImageField(upload_to='services_images/')),
                ('service_description', models.TextField(max_length=250)),
                ('service_category', models.CharField(choices=[('all', 'all'), ('tech', 'Technology'), ('science', 'Science'), ('arts', 'Arts'), ('business', 'Business'), ('finance', 'Finance'), ('health', 'Health & Wellness'), ('education', 'Education'), ('sports', 'Sports'), ('gaming', 'Gaming'), ('entertainment', 'Entertainment'), ('travel', 'Travel & Tourism'), ('food', 'Food & Cooking'), ('fashion', 'Fashion & Beauty'), ('automobile', 'Automobiles'), ('real_estate', 'Real Estate'), ('music', 'Music'), ('movies', 'Movies & TV Shows'), ('cryptocurrency', 'Cryptocurrency'), ('environment', 'Environment & Sustainability'), ('ai', 'Artificial Intelligence')], default='all', max_length=50)),
                ('service_country', models.CharField(choices=[('NG', 'Nigeria')], default='All', max_length=50)),
                ('service_state', models.CharField(choices=[('All', 'All'), ('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara'), ('Abuja', 'Abuja')], default='All', max_length=50)),
                ('service_city', models.CharField(choices=[('All', 'All'), ('Aba', 'Aba'), ('Umuahia', 'Umuahia'), ('Yola', 'Yola'), ('Mubi', 'Mubi'), ('Uyo', 'Uyo'), ('Eket', 'Eket'), ('Awka', 'Awka'), ('Onitsha', 'Onitsha'), ('Nnewi', 'Nnewi'), ('Bauchi', 'Bauchi'), ('Azare', 'Azare'), ('Yenagoa', 'Yenagoa'), ('Makurdi', 'Makurdi'), ('Otukpo', 'Otukpo'), ('Maiduguri', 'Maiduguri'), ('Biu', 'Biu'), ('Calabar', 'Calabar'), ('Ikom', 'Ikom'), ('Warri', 'Warri'), ('Asaba', 'Asaba'), ('Sapele', 'Sapele'), ('Abakaliki', 'Abakaliki'), ('Benin City', 'Benin City'), ('Auchi', 'Auchi'), ('Ado Ekiti', 'Ado Ekiti'), ('Enugu', 'Enugu'), ('Nsukka', 'Nsukka'), ('Gombe', 'Gombe'), ('Owerri', 'Owerri'), ('Orlu', 'Orlu'), ('Dutse', 'Dutse'), ('Kaduna', 'Kaduna'), ('Zaria', 'Zaria'), ('Kano', 'Kano'), ('Wudil', 'Wudil'), ('Katsina', 'Katsina'), ('Funtua', 'Funtua'), ('Birnin Kebbi', 'Birnin Kebbi'), ('Lokoja', 'Lokoja'), ('Anyigba', 'Anyigba'), ('Ilorin', 'Ilorin'), ('Offa', 'Offa'), ('Ikeja', 'Ikeja'), ('Badagry', 'Badagry'), ('Epe', 'Epe'), ('Ikorodu', 'Ikorodu'), ('Surulere', 'Surulere'), ('Lafia', 'Lafia'), ('Keffi', 'Keffi'), ('Minna', 'Minna'), ('Bida', 'Bida'), ('Abeokuta', 'Abeokuta'), ('Sagamu', 'Sagamu'), ('Akure', 'Akure'), ('Ondo', 'Ondo'), ('Osogbo', 'Osogbo'), ('Ile Ife', 'Ile Ife'), ('Ibadan', 'Ibadan'), ('Ogbomoso', 'Ogbomoso'), ('Jos', 'Jos'), ('Port Harcourt', 'Port Harcourt'), ('Bonny', 'Bonny'), ('Sokoto', 'Sokoto'), ('Jalingo', 'Jalingo'), ('Damaturu', 'Damaturu'), ('Potiskum', 'Potiskum'), ('Gusau', 'Gusau'), ('Garki', 'Garki'), ('Maitama', 'Maitama'), ('Wuse', 'Wuse')], default='All', max_length=50)),
                ('service_provider_name', models.CharField(max_length=200)),
                ('service_provider_expertise', models.TextField(max_length=500)),
                ('service_provider_experience_year', models.PositiveIntegerField(blank=True, null=True)),
                ('service_provider_email', models.CharField(max_length=1000)),
                ('service_provider_phone', models.CharField(max_length=15)),
                ('other_service_a', models.CharField(blank=True, max_length=50, null=True)),
                ('other_service_b', models.CharField(blank=True, max_length=50, null=True)),
                ('other_service_c', models.CharField(blank=True, max_length=50, null=True)),
                ('other_service_d', models.CharField(blank=True, max_length=50, null=True)),
                ('other_service_e', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
