# Generated by Django 5.1.6 on 2025-04-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_services_other_service_d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
