# Generated by Django 5.1.6 on 2025-04-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_products_is_paid_services_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcategory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('published', 'Published')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='product_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('published', 'Published')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='services',
            name='service_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('published', 'Published')], default='pending', max_length=20),
        ),
    ]
