# Generated by Django 5.1.6 on 2025-04-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_locationcategory_status_products_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='user_name',
            field=models.CharField(default='anonymous', max_length=250),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='user_name',
            field=models.CharField(default='anonymous', max_length=250),
        ),
    ]
